// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package hyper

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (DataDomeInterstitialInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*DataDomeInterstitialInput) UnmarshalJSON([]byte) error        { return nil }
func (DataDomeInterstitialInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*DataDomeInterstitialInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DataDomeInterstitialInput *DataDomeInterstitialInput

func (DataDomeSliderInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*DataDomeSliderInput) UnmarshalJSON([]byte) error        { return nil }
func (DataDomeSliderInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*DataDomeSliderInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DataDomeSliderInput *DataDomeSliderInput

func (DataDomeTagsInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*DataDomeTagsInput) UnmarshalJSON([]byte) error        { return nil }
func (DataDomeTagsInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*DataDomeTagsInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DataDomeTagsInput *DataDomeTagsInput

func (DynamicInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*DynamicInput) UnmarshalJSON([]byte) error        { return nil }
func (DynamicInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*DynamicInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DynamicInput *DynamicInput

func (Headers) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Headers) UnmarshalJSON([]byte) error        { return nil }
func (Headers) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Headers) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Headers *Headers

func (KasadaHeaders) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*KasadaHeaders) UnmarshalJSON([]byte) error        { return nil }
func (KasadaHeaders) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*KasadaHeaders) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_KasadaHeaders *KasadaHeaders

func (KasadaPayloadInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*KasadaPayloadInput) UnmarshalJSON([]byte) error        { return nil }
func (KasadaPayloadInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*KasadaPayloadInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_KasadaPayloadInput *KasadaPayloadInput

func (KasadaPowInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*KasadaPowInput) UnmarshalJSON([]byte) error        { return nil }
func (KasadaPowInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*KasadaPowInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_KasadaPowInput *KasadaPowInput

func (PixelInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*PixelInput) UnmarshalJSON([]byte) error        { return nil }
func (PixelInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*PixelInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PixelInput *PixelInput

func (ReeseInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ReeseInput) UnmarshalJSON([]byte) error        { return nil }
func (ReeseInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ReeseInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReeseInput *ReeseInput

func (SbsdInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SbsdInput) UnmarshalJSON([]byte) error        { return nil }
func (SbsdInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SbsdInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SbsdInput *SbsdInput

func (SensorInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SensorInput) UnmarshalJSON([]byte) error        { return nil }
func (SensorInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SensorInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SensorInput *SensorInput

func (UtmvcInput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UtmvcInput) UnmarshalJSON([]byte) error        { return nil }
func (UtmvcInput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UtmvcInput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UtmvcInput *UtmvcInput

func (apiResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*apiResponse) UnmarshalJSON([]byte) error        { return nil }
func (apiResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*apiResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_apiResponse *apiResponse

func (kasadaPayloadOutput) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*kasadaPayloadOutput) UnmarshalJSON([]byte) error        { return nil }
func (kasadaPayloadOutput) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*kasadaPayloadOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_kasadaPayloadOutput *kasadaPayloadOutput
